### ISSUE TITLE
[PE-D] output for create shelf and remove shelf command differs from UG (UG is not updated to reflect this)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#145] opened 2021-10-30 17:30 UTC
![image.png](https://raw.githubusercontent.com/avellinwong01/ped/main/files/47e8959d-720a-4729-8d86-f4b2eac7d2e8.png)

![image.png](https://raw.githubusercontent.com/avellinwong01/ped/main/files/46e37598-413f-4620-aed9-b4e7b0348bd1.png)

Expected output for create shelf and remove shelf command is shown to be nothing on UG

-------------
Labels: `severity.High` `type.DocumentationBug`
original: avellinwong01/ped#14

**Comment by zh1huang** [comment] 2021-10-31 01:15
Duplicate of #164

**Closed by zh1huang** 2021-10-31 01:15 UTC
