### ISSUE TITLE
[PE-D] Expected Outcome in documentation missing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#160] opened 2021-10-30 19:24 UTC
Most of the expected outcome for commands seem to be missing in the UG.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: mohamedirfansh/ped#7

**Comment by zh1huang** [comment] 2021-10-31 01:09
Duplicate of #164

**Closed by zh1huang** 2021-10-31 01:09 UTC
