### ISSUE TITLE
[PE-D] Documentation error in get function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#157] opened 2021-10-30 19:17 UTC
![1635500416(1).png](https://raw.githubusercontent.com/Mist0919/ped/main/files/fce0ed0a-ffb9-4880-b59c-8e2f2a67910c.png)
Strange message displayed for the container-does-not-exist error.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Mist0919/ped#5

**Comment by zh1huang** [comment] 2021-10-31 01:21
Duplicate of #122

**Closed by zh1huang** 2021-10-31 01:21 UTC
