### ISSUE TITLE
[PE-D] Quickstart no.4 image is missing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-4/tp#161] opened 2021-10-30 19:32 UTC
Image for no. 4 in quickstart missing.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: mohamedirfansh/ped#8

**Comment by zh1huang** [comment] 2021-10-31 01:17
Duplicate of #123

**Closed by zh1huang** 2021-10-31 01:17 UTC
